spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee_administration
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: "mother_of_all_omelettes"
  subject: "user_details"
  issuer: "Employee_Administration_Server"
  expiration_period_minutes: 120